<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ResiSeeder extends Seeder
{
    public function run(): void
    {
        // Cabang IDs: 1=Jakarta, 2=Bandung, 3=Surabaya, 4=Medan, 5=Makassar
        // Layanan IDs: 1=Reguler(9000/kg), 2=Express(15000/kg), 3=Kargo(6000/kg), 4=SameDay(25000/kg)
        // Pelanggan IDs: 1-20, User ID: 1

        $resiData = [
            [
                'nomor_resi'       => 'SLC-20260929-0001',
                'pelanggan_id'     => 1,
                'cabang_asal_id'   => 1,
                'cabang_tujuan_id' => 3,
                'layanan_id'       => 1,
                'user_id'          => 1,
                'nama_penerima'    => 'Budi Santoso',
                'telepon_penerima' => '081234567890',
                'alamat_penerima'  => 'Jl. Raya Darmo No. 12, Surabaya Pusat',
                'berat_aktual'     => 2.00,
                'panjang'          => 30,
                'lebar'            => 20,
                'tinggi'           => 15,
                'berat_tagih'      => 2.00,
                'nilai_barang'     => 500000,
                'biaya_dasar'      => 18000,
                'diskon'           => 0,
                'asuransi'         => 0,
                'total_biaya'      => 18000,
                'status'           => 'terkirim',
                'catatan'          => 'Paket elektronik, harap hati-hati',
                'created_at'       => now()->subDays(7),
                'updated_at'       => now()->subDays(5),
            ],
            [
                'nomor_resi'       => 'SLC-20260929-0002',
                'pelanggan_id'     => 3,
                'cabang_asal_id'   => 2,
                'cabang_tujuan_id' => 4,
                'layanan_id'       => 2,
                'user_id'          => 1,
                'nama_penerima'    => 'Siti Rahayu',
                'telepon_penerima' => '082198765432',
                'alamat_penerima'  => 'Jl. Gatot Subroto No. 45, Medan Baru',
                'berat_aktual'     => 1.50,
                'panjang'          => 25,
                'lebar'            => 15,
                'tinggi'           => 10,
                'berat_tagih'      => 1.50,
                'nilai_barang'     => 1500000,
                'biaya_dasar'      => 22500,
                'diskon'           => 2000,
                'asuransi'         => 3000,
                'total_biaya'      => 23500,
                'status'           => 'transit',
                'catatan'          => null,
                'created_at'       => now()->subDays(3),
                'updated_at'       => now()->subDays(2),
            ],
            [
                'nomor_resi'       => 'SLC-20260929-0003',
                'pelanggan_id'     => 5,
                'cabang_asal_id'   => 3,
                'cabang_tujuan_id' => 5,
                'layanan_id'       => 3,
                'user_id'          => 1,
                'nama_penerima'    => 'Ahmad Fauzi',
                'telepon_penerima' => '085312345678',
                'alamat_penerima'  => 'Jl. Pettarani No. 88, Makassar',
                'berat_aktual'     => 15.00,
                'panjang'          => 60,
                'lebar'            => 40,
                'tinggi'           => 30,
                'berat_tagih'      => 15.00,
                'nilai_barang'     => 3000000,
                'biaya_dasar'      => 90000,
                'diskon'           => 5000,
                'asuransi'         => 6000,
                'total_biaya'      => 91000,
                'status'           => 'pickup',
                'catatan'          => 'Barang fragile, gunakan bubble wrap',
                'created_at'       => now()->subDays(1),
                'updated_at'       => now()->subDays(1),
            ],
            [
                'nomor_resi'       => 'SLC-20260929-0004',
                'pelanggan_id'     => 7,
                'cabang_asal_id'   => 4,
                'cabang_tujuan_id' => 1,
                'layanan_id'       => 4,
                'user_id'          => 1,
                'nama_penerima'    => 'Dewi Lestari',
                'telepon_penerima' => '087765432100',
                'alamat_penerima'  => 'Jl. Sudirman No. 77, Jakarta Pusat',
                'berat_aktual'     => 0.80,
                'panjang'          => 20,
                'lebar'            => 15,
                'tinggi'           => 8,
                'berat_tagih'      => 1.00,
                'nilai_barang'     => 750000,
                'biaya_dasar'      => 25000,
                'diskon'           => 0,
                'asuransi'         => 1500,
                'total_biaya'      => 26500,
                'status'           => 'delivery',
                'catatan'          => 'Hubungi penerima 30 menit sebelum tiba',
                'created_at'       => now()->subHours(5),
                'updated_at'       => now()->subHours(2),
            ],
            [
                'nomor_resi'       => 'SLC-20260929-0005',
                'pelanggan_id'     => 9,
                'cabang_asal_id'   => 5,
                'cabang_tujuan_id' => 2,
                'layanan_id'       => 1,
                'user_id'          => 1,
                'nama_penerima'    => 'Rizki Pratama',
                'telepon_penerima' => '089988776655',
                'alamat_penerima'  => 'Jl. Asia Afrika No. 10, Bandung',
                'berat_aktual'     => 3.50,
                'panjang'          => 35,
                'lebar'            => 25,
                'tinggi'           => 20,
                'berat_tagih'      => 3.50,
                'nilai_barang'     => 200000,
                'biaya_dasar'      => 31500,
                'diskon'           => 1500,
                'asuransi'         => 0,
                'total_biaya'      => 30000,
                'status'           => 'pending',
                'catatan'          => null,
                'created_at'       => now()->subHours(1),
                'updated_at'       => now()->subHours(1),
            ],
            [
                'nomor_resi'       => 'SLC-20260929-0006',
                'pelanggan_id'     => 11,
                'cabang_asal_id'   => 1,
                'cabang_tujuan_id' => 2,
                'layanan_id'       => 2,
                'user_id'          => 1,
                'nama_penerima'    => 'Nurul Hidayah',
                'telepon_penerima' => '081345678901',
                'alamat_penerima'  => 'Jl. Dago No. 23, Bandung Utara',
                'berat_aktual'     => 1.00,
                'panjang'          => null,
                'lebar'            => null,
                'tinggi'           => null,
                'berat_tagih'      => 1.00,
                'nilai_barang'     => 0,
                'biaya_dasar'      => 15000,
                'diskon'           => 0,
                'asuransi'         => 0,
                'total_biaya'      => 15000,
                'status'           => 'terkirim',
                'catatan'          => 'Dokumen penting',
                'created_at'       => now()->subDays(10),
                'updated_at'       => now()->subDays(9),
            ],
            [
                'nomor_resi'       => 'SLC-20260929-0007',
                'pelanggan_id'     => 13,
                'cabang_asal_id'   => 2,
                'cabang_tujuan_id' => 3,
                'layanan_id'       => 3,
                'user_id'          => 1,
                'nama_penerima'    => 'Hendra Wijaya',
                'telepon_penerima' => '082156781234',
                'alamat_penerima'  => 'Jl. Pemuda No. 55, Surabaya Timur',
                'berat_aktual'     => 22.00,
                'panjang'          => 80,
                'lebar'            => 50,
                'tinggi'           => 40,
                'berat_tagih'      => 26.67,
                'nilai_barang'     => 5000000,
                'biaya_dasar'      => 160020,
                'diskon'           => 10000,
                'asuransi'         => 10000,
                'total_biaya'      => 160020,
                'status'           => 'gagal',
                'catatan'          => 'Alamat tidak ditemukan, paket dikembalikan',
                'created_at'       => now()->subDays(14),
                'updated_at'       => now()->subDays(12),
            ],
            [
                'nomor_resi'       => 'SLC-20260929-0008',
                'pelanggan_id'     => 15,
                'cabang_asal_id'   => 3,
                'cabang_tujuan_id' => 4,
                'layanan_id'       => 1,
                'user_id'          => 1,
                'nama_penerima'    => 'Rina Marlina',
                'telepon_penerima' => '085799001122',
                'alamat_penerima'  => 'Jl. Sisingamangaraja No. 30, Medan Selatan',
                'berat_aktual'     => 4.00,
                'panjang'          => 40,
                'lebar'            => 30,
                'tinggi'           => 25,
                'berat_tagih'      => 4.00,
                'nilai_barang'     => 800000,
                'biaya_dasar'      => 36000,
                'diskon'           => 3000,
                'asuransi'         => 1600,
                'total_biaya'      => 34600,
                'status'           => 'transit',
                'catatan'          => null,
                'created_at'       => now()->subDays(4),
                'updated_at'       => now()->subDays(3),
            ],
            [
                'nomor_resi'       => 'SLC-20260929-0009',
                'pelanggan_id'     => 17,
                'cabang_asal_id'   => 4,
                'cabang_tujuan_id' => 5,
                'layanan_id'       => 4,
                'user_id'          => 1,
                'nama_penerima'    => 'Fajar Nugroho',
                'telepon_penerima' => '081122334455',
                'alamat_penerima'  => 'Jl. Urip Sumoharjo No. 15, Makassar Utara',
                'berat_aktual'     => 0.50,
                'panjang'          => 15,
                'lebar'            => 10,
                'tinggi'           => 5,
                'berat_tagih'      => 1.00,
                'nilai_barang'     => 250000,
                'biaya_dasar'      => 25000,
                'diskon'           => 0,
                'asuransi'         => 0,
                'total_biaya'      => 25000,
                'status'           => 'pickup',
                'catatan'          => 'Paket medis, prioritas tinggi',
                'created_at'       => now()->subHours(3),
                'updated_at'       => now()->subHours(3),
            ],
            [
                'nomor_resi'       => 'SLC-20260929-0010',
                'pelanggan_id'     => 20,
                'cabang_asal_id'   => 5,
                'cabang_tujuan_id' => 1,
                'layanan_id'       => 2,
                'user_id'          => 1,
                'nama_penerima'    => 'Anisa Putri',
                'telepon_penerima' => '089911223344',
                'alamat_penerima'  => 'Jl. Kebon Sirih No. 5, Jakarta Pusat',
                'berat_aktual'     => 2.50,
                'panjang'          => 30,
                'lebar'            => 20,
                'tinggi'           => 15,
                'berat_tagih'      => 2.50,
                'nilai_barang'     => 2000000,
                'biaya_dasar'      => 37500,
                'diskon'           => 2500,
                'asuransi'         => 4000,
                'total_biaya'      => 39000,
                'status'           => 'delivery',
                'catatan'          => 'Tanda tangan penerima diperlukan',
                'created_at'       => now()->subHours(6),
                'updated_at'       => now()->subHours(1),
            ],
        ];

        DB::table('resi')->insert($resiData);
    }
}
